services:
  homarr:
    container_name: homarr
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - homarr-appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=
    ports:
      - 7575:7575
    image: ghcr.io/homarr-labs/homarr:latest

volumes:
  homarr-appdata:
