services:
  n8n:
    container_name: n8n
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
      - n8n_ssh:/home/node/.ssh
    env_file:
      - stack.env
    image: docker.n8n.io/n8nio/n8n
    restart: always

volumes:
  n8n_data:
  n8n_ssh:
