services:
  uptime-kuma:
    container_name: uptime-kuma
    ports:
      - 3001:3001
    volumes:
      - uptime-kuma:/app/data
    image: louislam/uptime-kuma:1
    restart: always

volumes:
  uptime-kuma:
