services:
  n8n:
    container_name: n8n
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - N8N_SECURE_COOKIE=false
    image: docker.n8n.io/n8nio/n8n
    restart: always
volumes:
  n8n_data:

